import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/component/sideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row h-screen w-screen overflow-hidden">
          <div className="flex-shrink-0">
            <Sidebar/>
          </div>
          <div className="flex-1 h-full overflow-y-auto">
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
