export const TYPES = {
  
  USER_LOGIN_LOADING: 'USER_LOGIN_LOADING',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  
  USER_LOGOUT_LOADING: 'USER_LOGOUT_LOADING',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT',
  USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

  USER_REGISTER_LOADING: 'USER_REGISTER_LOADING',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  CREATE_HOSPITAL_LOADING: 'CREATE_HOSPITAL_LOADING',
  CREATE_HOSPITAL_SUCCESS: 'CREATE_HOSPITAL_SUCCESS',
  CREATE_HOSPITAL_FAILURE: 'CREATE_HOSPITAL_FAILURE',

  GET_HOSPITALS_LOADING: 'GET_HOSPITALS_LOADING',
  GET_HOSPITALS_SUCCESS: 'GET_HOSPITALS_SUCCESS',
  GET_HOSPITALS_FAILURE: 'GET_HOSPITALS_FAILURE',

   CREATE_ADMIN_LOADING: "CREATE_ADMIN_LOADING",
  CREATE_ADMIN_SUCCESS: "CREATE_ADMIN_SUCCESS",
  CREATE_ADMIN_FAILURE: "CREATE_ADMIN_FAILURE",

  
  
};
